config/routes.rb
Rails.application.routes.draw do

  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get 'login', to: 'pages#login', as: :new_user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  root to: "pages#index"

  get "/download_backup", to: "pages#download_backup"

  resources :purchase_orders

  get "/warehouse", to: "warehouse#index", as: :warehouse
  get "/warehouse/:id", to: "warehouse#show", as: :warehouse_show

  resources :items

  namespace :administration do
    get "/dashboard", to: "pages#index" 
    resources :users
    resources :suppliers
    resources :equipments
    resources :clients
  end

  draw :administration
  draw :api
end

app/models/client.rb
class Client < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  #validates :email, presence: true, uniqueness: true
  #validates :contact_number, presence: true
  validates :address, presence: true

  has_many :purchase_orders

  def to_s
    name
  end
end

app/controllers/administration/clients_controller.rb
module Administration
  class ClientsController < ApplicationController
    before_action :authenticate_user!
    
    def index
      @clients = Client.all
    end

    def new
      @client = Client.new
    end

    def create
      @client = Client.new(client_params)

      if @client.save
        flash[:success] = "Successfully Created Record."
        redirect_to administration_client_path(@client)
      else 
        render "new"
      end
    end

    def show
      @client = Client.find(params[:id])
    end

    def edit
      @client = Client.find(params[:id])
    end

    def update
      @client = Client.find(params[:id])
 
      if @client.update(client_params)
        flash[:success] = "Successfully Updated Record."
        redirect_to administration_client_path(@client)
      else
        flash[:error] = "Error Saving Record. #{@client.errors.full_messages}"
        render "edit"
      end
    end

    def destroy
      @client = Client.find(params[:id])
      @client.destroy
      flash[:success] = "Successfully Deleted Record."
      redirect_to administration_clients_path
    end
    
    def client_params
      params.require(:client).permit!
    end
  end
end

app/controllers/administration/equipments_controller.rb
module Administration
  class EquipmentsController < ApplicationController
    before_action :authenticate_user!
    
    def index
      @equipments = Equipment.all
    end

    def new
      @equipment = Equipment.new
    end

    def create
      @equipment = Equipment.new(equipment_params)

      if @equipment.save
        flash[:success] = "Successfully Created Record."
        redirect_to administration_equipment_path(@equipment)
      else 
        render "new"
      end
    end

    def show
      @equipment = Equipment.find(params[:id])
    end

    def edit
      @equipment = Equipment.find(params[:id])
    end

    def update
      @equipment = Equipment.find(params[:id])
 
      if @equipment.update(equipment_params)
        flash[:success] = "Successfully Updated Record."
        redirect_to administration_equipment_path(@equipment)
      else
        flash[:error] = "Error Saving Record. #{@equipment.errors.full_messages}"
        render "edit"
      end
    end

    def destroy
      @equipment = Equipment.find(params[:id])
      @equipment.destroy
      flash[:success] = "Successfully Deleted Record."
      redirect_to administration_equipments_path
    end
    
    def equipment_params
      params.require(:equipment).permit!
    end
  end
end

app/controllers/administration/pages_controller.rb
module Administration
  class PagesController < ApplicationController
    before_action :authenticate_user!
    
    def index
      @users = User.all
    end

  end
end

app/controllers/administration/suppliers_controller.rb
module Administration
  class SuppliersController < ApplicationController
    before_action :authenticate_user!
    
    def index
      @suppliers = Supplier.all
    end

    def new
      @supplier = Supplier.new
    end

    def create
      @supplier = Supplier.new(supplier_params)

      if @supplier.save
        flash[:success] = "Successfully Created Record."
        redirect_to administration_supplier_path(@supplier)
      else 
        render "new"
      end
    end

    def show
      @supplier = Supplier.find(params[:id])
    end

    def edit
      @supplier = Supplier.find(params[:id])
    end

    def update
      @supplier = Supplier.find(params[:id])
 
      if @supplier.update(supplier_params)
        flash[:success] = "Successfully Updated Record."
        redirect_to administration_supplier_path(@supplier)
      else
        flash[:error] = "Error Saving Record. #{@supplier.errors.full_messages}"
        render "edit"
      end
    end

    def destroy
      @supplier = Supplier.find(params[:id])
      @supplier.destroy
      flash[:success] = "Successfully Deleted Record."
      redirect_to administration_suppliers_path
    end
    
    def supplier_params
      params.require(:supplier).permit!
    end
  end
end

app/controllers/administration/users_controller.rb
module Administration
  class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :authenticate_admin!

    def index
      @users = User.all
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)

      if @user.save
        redirect_to administration_user_path(@user)
      else 
        render "new"
      end
    end

    def show
      @user = User.find(params[:id])
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])
 
      if @user.update(user_params)
        redirect_to administration_user_path(@user)
      else
        render "edit"
      end
    end

    def destroy
      @user = User.find(params[:id])
      @user.destroy
      flash[:success] = "Successfully Deleted Record."
      redirect_to administration_users_path
    end
    
    def user_params
      params.require(:user).permit!
    end
  end
end

app/views/administration/clients/_form.html.haml
= simple_form_for [:administration, @client] do |f|
  .row
    .col-md-6.col-xs-12
      .form-group
        = f.input :name, input_html: { class: 'form-control' }
    .col-md-6.col-xs-12
      .form-group 
        = f.input :address, input_html: { class: 'form-control' }
  .row
    .col-md-6.col-xs-12
      .form-group
        = f.input :email, input_html: { class: 'form-control' }
    .col-md-6.col-xs-12
      .form-group
        = f.input :contact_number, input_html: { class: 'form-control' }
  .row
    .col-md-12
      = f.submit "SAVE", class: "btn btn-primary"
      - if @client.new_record?
        = link_to administration_clients_path, class: 'btn btn-danger' do
          .fa.fa-times
          Cancel
      - else
        = link_to administration_client_path(@client), class: 'btn btn-danger' do
          .fa.fa-times
          Cancel

%hr
    

app/views/administration/clients/_index_header.html.haml
%ol.breadcrumb
  %li.breadcrumb-item
    = link_to administration_dashboard_path do
      .fa.fa-lock
      Administration
  %li.breadcrumb-item
    .fa.fa-boxes
    Clients

app/views/administration/clients/_index_list.html.haml
.row
  .col-md-6.col-xs-12
    %h3
      List of Clients
  .col-md-6.col-xs-12
    .text-right
      = link_to new_administration_client_path, class: "btn btn-secondary add_user" do
        %i.fa.fa-plus
        Add New Client

.row
  .col
    .table-responsive{:style => "margin-top: 1%;"}
      %table.table.table-bordered.table-hover.table-sm
        %thead
          %tr
            = form_tag send("administration_clients_path"), method: "GET" do
              
              %td
                = text_field_tag :name, @name, placeholder: "Name", class: "form-control"
              %td
                %center
                  = button_tag "Search", class: "btn btn-light"
                  = link_to "Clear", administration_users_path, class: "btn btn-light"
          %tr.header-gray
            %th Name
            %th Actions
        %tbody 
          - if current_user.admin?
            - @clients.each do |client|
              %tr
                %td= client.name
                %td
                  = link_to administration_client_path(client.id), class: "btn btn-light" do
                    Details
                  - if current_user.admin?
                    &nbsp;
                    = link_to edit_administration_client_path(client.id), class: "btn btn-info" do
                      Edit

app/views/administration/clients/_show_header.html.haml
%ol.breadcrumb
  %li.breadcrumb-item
    = link_to administration_dashboard_path do
      .fa.fa-lock
      Administration
  %li.breadcrumb-item
    = link_to administration_clients_path do
      .fa.fa-boxes
      Clients
  %li.breadcrumb-item
    .fa.fa-user
    #{@client.to_s}

app/views/administration/clients/edit.html.haml
.container
  .jumbotron
    %h2
      %i.fa.fa-boxes
      Edit Client #{@client}
    %hr
    = render partial: "form"

app/views/administration/clients/index.html.haml
= render partial: "index_header"

.container
  .row
    .col
      .card
        .card-body
          = render partial: "index_list"

app/views/administration/clients/new.html.haml
.container
  .jumbotron
    %h2
      %i.fa.fa-boxes
      New Client Form
    %hr
    = render partial: "form"

app/views/administration/clients/show.html.haml
= render partial: "show_header"
.container
  .jumbotron{:style => "margin-top: 2%;"}
    .row
      .col-md-12
        %h2.text-muted
          .fa.fa-noxes
          #{@client.name}
        %span.text-danger
        %hr
        %table.table.table-bordered.table-sm
          %tbody
            %tr
              %th{ width: "25%" }
                Address
              %td
                #{@client.address}
            %tr
              %th
                Email
              %td
                #{@client.email}
            %tr
              %th
                Contact Number
              %td
                #{@client.contact_number}
        %hr
        = link_to administration_client_path(@client), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } do
          .fa.fa-times
          Delete Record