config/routes.rb
Rails.application.routes.draw do

  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get 'login', to: 'pages#login', as: :new_user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  root to: "pages#index"

  get "/download_backup", to: "pages#download_backup"

  resources :purchase_orders

  get "/warehouse", to: "warehouse#index", as: :warehouse
  get "/warehouse/:id", to: "warehouse#show", as: :warehouse_show

  resources :items

  namespace :administration do
    get "/dashboard", to: "pages#index" 
    resources :users
    resources :suppliers
    resources :equipments
    resources :clients
  end

  draw :administration
  draw :api
end

app/views/shared/_header.html.haml
%header.app-header.navbar
  = link_to root_path, class: "navbar-brand" do
    = image_tag "logo.png", width: "89"
  %button.navbar-toggler.aside-menue-toggler.sidebar-toggler.d-md-down-none{ data: { toggle: 'sidebar-show' } }
    %span.navbar-toggler-icon
  %ul.nav.navbar-nav.d-md.down-none
  %ul.nav.navbar-nav.ml-auto
    %li.nav-item.dropdown
      = link_to "#", class: "nav-link dropdown-toggle nav-link", data: { toggle: "dropdown" }, role: "button", "aria-hashpopup" => "true", "aria-expanded" => "true" do
        %span.d-md-down-none
          #{current_user.email}
      .dropdown-menu.dropdown-menu-right
        .dropdown-header.text-center
          Settings
        = link_to "#", class: "dropdown-item" do
          %i.fa.fa-sync
          Change Password
        = link_to destroy_user_session_path, method: :delete, class: 'dropdown-item' do
          %i.fa.fa-times
          Logout
  %button.navbar-toggler.sidebar-toggler.d-md-down-none{ data: { toggle: 'sidebar-show' } }
    %span.navbar-toggler-icon

app/views/shared/_po_progress.html.haml
.row
  .col
    %hr.po-progress.done
  .col-auto
    Pending
  .col
    %hr.po-progress

app/views/shared/_sidebar.html.haml
.sidebar
  %nav.sidebar-nav.open
    %ul.nav
      %li.nav-title
        Navigation
      %li.nav-item
        = link_to root_path, class: "nav-link #{params[:controller] == 'pages' && params[:action] == 'index' ? 'active' : ''}" do
          %i.nav-icon.fa.fa-tachometer-alt
          Dashboard
        = link_to purchase_orders_path, class: "nav-link #{params[:controller] == 'purchase_orders' ? 'active': '' }" do
          %i.nav-icon.fa.fa-file
          Purchase Orders
        = link_to warehouse_path, class: "nav-link #{params[:controller] == 'warehouse' ? 'active' : ''}" do
          %i.nav-icon.fa.fa-warehouse
          Warehouse
        = link_to items_path, class: "nav-link #{params[:controller] == 'items' ? 'active' : ''}" do
          %i.nav-icon.fa.fa-boxes
          Items
      %li.nav-title
        Administration
      %li.nav-item
        = link_to "/administration/dashboard", class: "nav-link #{params[:controller] == 'administration/pages' && params[:action] == 'index' ? 'active' : ''}" do
          %i.nav-icon.fa.fa-tachometer-alt
          Dashboard
      %li.nav-item
        = link_to administration_users_path, class: "nav-link #{params[:controller] == 'users' && params[:action] == 'index' ? 'active' : ''}" do
          %i.nav-icon.fa.fa-users
          Users
      %li.nav-item
        = link_to administration_clients_path, class: "nav-link #{params[:controller] == 'clients' && params[:action] == 'index' ? 'active' : ''}" do
          %i.nav-icon.fa.fa-user
          Clients
      %li.nav-item
        = link_to administration_suppliers_path, class: "nav-link #{params[:controller] == 'suppliers' && params[:action] == 'index' ? 'active' : ''}" do
          %i.nav-icon.fa.fa-boxes
          Suppliers