config/routes.rb
Rails.application.routes.draw do

  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get 'login', to: 'pages#login', as: :new_user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  root to: "pages#index"

  get "/download_backup", to: "pages#download_backup"

  resources :purchase_orders

  get "/warehouse", to: "warehouse#index", as: :warehouse
  get "/warehouse/:id", to: "warehouse#show", as: :warehouse_show

  resources :items

  namespace :administration do
    get "/dashboard", to: "pages#index" 
    resources :users
    resources :suppliers
    resources :equipments
    resources :clients
  end

  draw :administration
  draw :api
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true

  before_validation :load_defaults

  def to_s
    name
  end

  def load_defaults
    if self.new_record?
      self.stock = 0
    end
  end
end

app/controllers/api/v1/items_controller.rb
module Api
  module V1
    class ItemsController < ApplicationController
      before_action :authenticate_user!

      def stock
        item              = Item.where(id: params[:id]).first
        transaction_type  = params[:transaction_type]
        remarks           = params[:remarks]
        quantity          = params[:quantity]

        config  = {
          item: item,
          transaction_type: transaction_type,
          remarks: remarks,
          quantity: quantity,
          user: current_user
        }

        errors  = ::Items::ValidateStock.new(
                    config: config
                  ).execute!

        if errors[:messages].size > 0
          render json: errors, status: 400
        else
          item  = ::Items::Stock.new(
                    config: config
                  ).execute!

          render json: { message: "ok" }
        end
      end

      def update_name
        item        = Item.where(id: params[:id]).first
        name = params[:name]

        config  = {
          item: item,
          name: name,
          user: current_user
        }

        errors  = ::Items::ValidateUpdateName.new(
                    config: config
                  ).execute!

        if errors[:messages].size > 0
          render json: errors, status: 400
        else
          item.update!(name: name)

          render json: { message: "ok" }
        end
      end

      def update_description
        item        = Item.where(id: params[:id]).first
        description = params[:description]

        config  = {
          item: item,
          description: description,
          user: current_user
        }

        errors  = ::Items::ValidateUpdateDescription.new(
                    config: config
                  ).execute!

        if errors[:messages].size > 0
          render json: errors, status: 400
        else
          item.update!(description: description)

          render json: { message: "ok" }
        end
      end
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_item!, only: [:edit, :show, :update, :destroy]

  def index
    @items  = Item.select("*")

    @q  = params[:q]

    if @q.present?
      @items  = @items.where(
                  "upper(name) LIKE ?",
                  "%#{@q.upcase}%"
                )
    end

    @items  = @items.order("name ASC").page(params[:page]).per(20)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    
    if @item.save
      redirect_to item_path(@item)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item)
    else
      render :edit
    end
  end

  def destroy
    @item.destroy!
    redirect_to items_path
  end

  def show
    @item_transactions  = ItemTransaction.where(
                            item_id: @item.id
                          ).order("transacted_at DESC")
  end

  private

  def item_params
    params.require(:item).permit!
  end

  def load_item!
    @item = Item.find(params[:id])
  end
end

app/views/items/_edit_header.html.haml
%ol.breadcrumb
  %li.breadcrumb-item
    = link_to warehouse_path do
      .fa.fa-warehouse
      Warehouse
  %li.breadcrumb-item
    = link_to items_path do
      .fa.fa-boxes
      Items
  %li.breadcrumb-item
    .fa.fa-pencil-alt
    Edit Item #{@item}
  %li.breadcrumb-menu.d-md-down-none

app/views/items/_form.html.haml
= simple_form_for @item do |f|
  .row
    .col-md-12
      .form-group
        = f.input :name, input_html: { class: 'form-control' }
    .col-md-12
      .form-group
        = f.input :description, input_html: { class: 'form-control' }
  .row
    .col-md-12
      = f.submit "SAVE", class: "btn btn-primary"
      - if @item.new_record?
        = link_to items_path, class: 'btn btn-danger' do
          .fa.fa-times
          Cancel
      - else
        = link_to item_path(@item), class: 'btn btn-danger' do
          .fa.fa-times
          Cancel

%hr
    

app/views/items/_index_filter.html.haml
= form_tag "", method: 'GET' do
  .row
    .col-md-10.col-xs-12
      .form-group
        %label
          Name
        = text_field_tag :q, @q, class: 'form-control', placeholder: 'Name'
    .col-md-2.col-xs-12
      .form-group
        %label
          Actions
        = button_tag type: 'submit', class: 'btn btn-info btn-block' do
          .fa.fa-search

app/views/items/_index_header.html.haml
%ol.breadcrumb
  %li.breadcrumb-item
    = link_to warehouse_path do
      .fa.fa-warehouse
      Warehouse
  %li.breadcrumb-item
    .fa.fa-boxes
    Items
  %li.breadcrumb-menu.d-md-down-none
    .btn-group
      = link_to new_item_path, class: "btn", id: "btn-new" do
        .fa.fa-plus
        New Item

app/views/items/_index_list.html.haml
%table.table.table-bordered.table-hover.table-sm
  %thead
    %tr
      %th
        Name
      %th.text-center
        Current Stock
  %tbody
    - @items.each do |item|
      %tr
        %td
          = link_to item_path(item) do
            %strong
              #{item}
        %td.text-center
          #{item.stock}
          

app/views/items/_new_header.html.haml
%ol.breadcrumb
  %li.breadcrumb-item
    = link_to warehouse_path do
      .fa.fa-warehouse
      Warehouse
  %li.breadcrumb-item
    = link_to items_path do
      .fa.fa-boxes
      Items
  %li.breadcrumb-item
    .fa.fa-plus
    New Item
  %li.breadcrumb-menu.d-md-down-none

app/views/items/_show_details.html.haml
%table.table.table-bordered.table-sm
  %tbody
    %tr
      %th{ width: "25%" }
        Name:
      %td
        #{@item.name}
    %tr
      %th
        Stock:
      %td
        #{@item.stock}
    %tr
      %th
        Description:
      %td
        %pre
          #{@item.description}

%hr

%h5
  Transaction Logs

- if @item_transactions.size > 0
  %table.table.table-bordered.table-sm
    %thead
      %tr
        %th{ width: "25%" }
          Transacted At
        %th{ width: "25%" }
          Transacted By
        %th.text-center{ width: "10%" }
          Quantity
        %th
          Remarks
    %tbody
      - @item_transactions.each do |o|
        %tr
          %td
            #{o.transacted_at.localtime.strftime("%B %d, %Y %H:%M")}
          %td
            #{o.data.with_indifferent_access[:user][:last_name]}, #{o.data.with_indifferent_access[:user][:first_name]}
          %td.text-center
            #{o.quantity}
            %br
            - if o.in?
              .badge.badge-info
                .fa.fa-download
                IN
            - elsif o.out?
              .badge.badge-danger
                .fa.fa-upload
                OUT
          %td
            %pre
              #{o.data.with_indifferent_access[:remarks]}
- else
  %p
    No transactions for this item

app/views/items/_show_header.html.haml
%ol.breadcrumb
  %li.breadcrumb-item
    = link_to items_path do
      .fa.fa-boxes
      Items
  %li.breadcrumb-item
    #{@item}
  %li.breadcrumb-menu.d-md-down-none
    .btn-group
      = link_to edit_item_path(@item), class: "btn", id: "btn-new" do
        .fa.fa-pencil-alt
        Edit Item

app/views/items/edit.html.haml
= render partial: "edit_header"

.container-fluid
  .row
    .col
      .card
        .card-body
          = render partial: "form"

app/views/items/index.html.haml
= render partial: "index_header"

.container-fluid
  .row
    .col
      .card
        .card-body
          = render partial: "index_filter"
          
          - if @items.size > 0
            = render partial: "index_list"
            = paginate @items
          - else
            %p
              No items found

app/views/items/new.html.haml
= render partial: "new_header"

.container-fluid
  .row
    .col
      .card
        .card-body
          = render partial: "form"

app/views/items/show.html.haml
= render partial: "show_header"

.container-fluid
  .row
    .col
      .card
        .card-body
          .text-right
            .btn-group
              = link_to "#", class: 'btn btn-primary', id: 'btn-add' do
                .fa.fa-plus
                Add Stock
              = link_to "#", class: 'btn btn-danger', id: 'btn-remove' do
                .fa.fa-minus
                Remove Stock
          %hr
          = render partial: "show_details"

#parameters{ data: { id: "#{@item.id}" } }
= render partial: "items/modals/stock"
= javascript_include_tag "items/Show"

:javascript
  $(document).ready(function() {
    var authenticityToken = $("meta[name='csrf-token']").attr('content');
    var $parameters       = $("#parameters");
    var itemId            = $parameters.data("id");

    Show.init({
      authenticityToken: authenticityToken,
      itemId: itemId
    });
  });